# nagios-notification-jabber
# .pre-commit-config.yaml


repos:
- repo: local
  hooks:
    - id: seed-isort-config
      name: seed-isort-config
      stages: [commit]
      language: system
      pass_filenames: false
      entry: seed-isort-config
      types: [python]
    - id: removestar
      name: removestar
      stages: [commit]
      language: system
      entry: removestar -i notification_jabber
      types: [python]
    - id: isort
      name: isort
      stages: [commit]
      language: system
      entry: isort
      types: [python]
    - id: black
      name: black
      stages: [commit]
      language: system
      entry: black notification_jabber.py tests
      types: [python]
    - id: yesqa
      name: yesqa
      stages: [commit]
      language: system
      pass_filenames: false
      entry: yesqa
      types: [python]
    - id: flake8
      name: flake8
      stages: [commit]
      language: system
      entry: flake8
      types: [python]
    - id: interrogate
      name: interrogate
      stages: [commit]
      language: system
      entry: interrogate . -I -M -e .direnv
      types: [python]
    - id: pylint
      name: pylint
      stages: [commit]
      language: system
      entry: pylint notification_jabber tests
      types: [python]
    - id: bandit
      name: bandit
      stages: [commit]
      language: system
      entry: bandit --ini=setup.cfg
      types: [python]
      pass_filenames: true
    - id: dodgy
      name: dodgy
      stages: [commit]
      language: system
      entry: dodgy
      types: [python]
      pass_filenames: false
    - id: darglint
      name: darglint
      stages: [commit]
      language: system
      entry: darglint
      types: [python]
    - id: mypy
      name: mypy
      stages: [commit]
      language: system
      entry: bash -c 'PYTHONPATH="$PYTHONPATH:$PWD" mypy'
      types: [python]
      pass_filenames: false
    - id: check-manifest
      name: check-manifest
      stages: [commit]
      language: system
      pass_filenames: false
      entry: check-manifest
      types: [python]
    - id: pyroma
      name: pyroma
      stages: [commit]
      language: system
      pass_filenames: false
      entry: pyroma -d .
      types: [python]
    - id: check-wheel-contents
      name: check-wheel-contents
      stages: [commit]
      language: system
      pass_filenames: false
      entry: bash -c 'make build -B && check-wheel-contents dist'
      types: [python]
    - id: dotenv-linter
      name: dotenv-linter
      entry: dotenv-linter
      language: system
      stages: [commit]
      types: [text]
      files: \.env*
      exclude: .envrc
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: name-tests-test
      - id: trailing-whitespace
