# nagios-notification-jabber
# .travis.yml


language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - |
      pip install pipenv
      pip install .[test-old-python]
script:
  - make tox
after_success:
  - make coveralls
