# -*- coding: utf-8 -*-

# notification-jabber
# notification_jabber.pyi

from typing import List, Tuple, Dict  # pylint: disable=W0611
from argparse import Namespace

from xmpp import Client, Message

__all__: List[str] = ...


VERSION: Tuple[int, int, int] = ...
__version__: str = ...


class NotificationJabber(object):

    MESSAGE_TYPE_CHAT: str = ...
    MESSAGE_TYPE_GROUP_CHAT: str = ...

    def __init__(self) -> None: ...
    def _get_options(self) -> Namespace: ...
    def _get_config(self) -> Dict[str, str]: ...
    def _get_connection(self) -> Client: ...
    def _get_message(self) -> Message: ...
    def notify(self) -> None: ...


def main() -> None: ...
